@extends('layouts.public')
@section('content')
@include('public.partials')
@php epimHero('À propos', 'Histoire, vision, mission et valeurs de EPIM Meknès.'); @endphp
<section class="section"><div class="container split"><div><span class="eyebrow">Notre histoire</span><h2>Une école construite autour de la compétence, de la confiance et de l’innovation.</h2><p>EPIM accompagne les jeunes, salariés et adultes en reconversion vers des métiers concrets. Notre pédagogie associe cours structurés, ateliers pratiques, évaluation continue, coaching, outils IA et liens avec les entreprises de la région.</p><p>Notre ambition est de former des profils fiables, autonomes et capables de contribuer rapidement dans des organisations marocaines qui se digitalisent.</p></div><aside class="director-card reveal"><div class="director-card__top"><div class="director-card__avatar">D</div><div><span class="eyebrow">Mot du directeur</span><h3>Former des talents utiles, confiants et prêts pour l’entreprise.</h3></div></div><p class="director-card__lead">À EPIM, nous croyons qu’une formation professionnelle réussie ne se limite pas à transmettre un programme. Elle doit donner à chaque stagiaire une méthode de travail, une discipline, une culture du résultat et la confiance nécessaire pour avancer dans son projet.</p><p>Notre engagement est d’offrir un cadre sérieux, proche des réalités du marché marocain, où l’apprentissage se construit par la pratique, l’accompagnement, l’IA appliquée et le contact avec les entreprises. Chaque parcours est pensé pour rapprocher nos stagiaires de l’emploi, du stage ou de la poursuite d’études.</p><div class="director-card__commitments"><span><i class="bi bi-check2-circle"></i> Exigence pédagogique</span><span><i class="bi bi-check2-circle"></i> Outils IA responsables</span><span><i class="bi bi-check2-circle"></i> Orientation employabilité</span></div><div class="director-card__signature"><div><strong>Direction EPIM</strong><small>École Professionnelle d’Informatique et de Management - Meknès</small></div><img src="{{ asset('images/epim-accreditation.webp') }}" alt="{{ __('site.accredited') }}"></div></aside></div></section>
<section class="section muted"><div class="container cards-3">@foreach([['Vision','Devenir une référence régionale de la formation professionnelle privée.'],['Mission','Former, accompagner et insérer des profils opérationnels.'],['Valeurs','Exigence, proximité, éthique, innovation et employabilité.']] as $v)<div class="feature reveal"><h3>{{ $v[0] }}</h3><p>{{ $v[1] }}</p></div>@endforeach</div></section>
<section class="section"><div class="container"><div class="section-head"><span class="eyebrow">Accréditations et partenariats</span><h2>Un environnement ouvert aux standards professionnels</h2></div><div class="accreditation-panel reveal"><img src="{{ asset('images/epim-accreditation.webp') }}" alt="{{ __('site.accredited') }}"><div><h3>{{ __('site.accredited') }}</h3><p>Ce label confirme la reconnaissance institutionnelle de l’établissement dans le cadre de la formation professionnelle privée au Maroc.</p></div></div><div class="logos">@foreach($partners as $p)<div><img src="{{ $p->logo_url }}" alt="{{ $p->name }}"><span>{{ $p->name }}</span></div>@endforeach</div></div></section>
<section class="section muted"><div class="container"><div class="section-head"><span class="eyebrow">Équipe pédagogique</span><h2>Des intervenants proches du terrain</h2></div><div class="cards-4">@foreach(['Responsable pédagogique','Formateur IT','Formatrice Gestion','Coach soft skills'] as $role)<div class="team"><img src="https://ui-avatars.com/api/?background=004B9C&color=fff&name={{ urlencode($role) }}"><h3>{{ $role }}</h3><p>Encadrement, suivi individuel et animation d’ateliers professionnels.</p></div>@endforeach</div></div></section>
@endsection
